services:
  postgres:
    image: postgres:15-alpine
    container_name: dkp_postgres_simple
    environment:
      POSTGRES_DB: dkp
      POSTGRES_USER: dkp
      POSTGRES_PASSWORD: dkp123
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dkp -d dkp"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dkp_redis_simple
    command: redis-server --appendonly yes
    volumes:
      - redis_test_data:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_test_data:
  redis_test_data: