# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0002_create_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('CAN_ACCEPT_PATIENTS', 'Can Accept Patients'), ('SURGERY_DONE', 'Surgery Done'), ('PATIENT_IN_THE_OR', 'Patient in the OR')], max_length=50)),
                ('content', models.TextField()),
                ('location_type', models.CharField(choices=[('operating_room', 'Operating Room'), ('ward', 'Ward')], max_length=20)),
                ('location_id', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='hospital.role')),
                ('sender_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='hospital.role')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]