# Generated by Django 5.2.7 on 2025-10-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Internal message code (readonly in admin)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "source_role",
                    models.CharField(
                        choices=[
                            ("Anesthetist", "Anesthetist"),
                            ("Nurse", "Nurse"),
                            ("Surgeon", "Surgeon"),
                        ],
                        help_text="Role that can send this message",
                        max_length=20,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("Anesthetist", "Anesthetist"),
                            ("Nurse", "Nurse"),
                            ("Surgeon", "Surgeon"),
                        ],
                        help_text="Role that will receive this message",
                        max_length=20,
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        help_text="Short English description shown on buttons",
                        max_length=100,
                    ),
                ),
                (
                    "full_description_en",
                    models.TextField(
                        help_text="Full English description explaining the message"
                    ),
                ),
                (
                    "short_description_pl",
                    models.CharField(
                        help_text="Short Polish description shown on buttons",
                        max_length=100,
                    ),
                ),
                (
                    "full_description_pl",
                    models.TextField(
                        help_text="Full Polish description explaining the message"
                    ),
                ),
                (
                    "button_color",
                    models.CharField(
                        default="danger",
                        help_text="Bootstrap button color class (danger, warning, success, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which buttons are displayed (lower numbers first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this message type is currently available",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Type",
                "verbose_name_plural": "Message Types",
                "ordering": ["display_order", "code"],
            },
        ),
    ]
