# Generated by Django 5.2.7 on 2025-10-09 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0004_messagelog_hospital_messagetype_hospital"),
        (
            "hospital",
            "0011_alter_operatingroom_name_alter_operatingroom_name_en_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagelog",
            name="location_id",
        ),
        migrations.RemoveField(
            model_name="messagelog",
            name="location_type",
        ),
        migrations.AddField(
            model_name="messagelog",
            name="operating_room",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_logs",
                to="hospital.operatingroom",
            ),
        ),
        migrations.AddField(
            model_name="messagelog",
            name="ward",
            field=models.ForeignKey(
                default=15,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_logs",
                to="hospital.ward",
            ),
        ),
    ]
