# Generated by Django 5.2.7 on 2025-10-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0005_remove_messagelog_location_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagelog",
            name="no_users_who_received",
            field=models.BooleanField(
                default=False,
                help_text="True if no users were connected to receive this message when it was sent",
            ),
        ),
    ]
