# Generated by Django 5.2.7 on 2025-10-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0006_messagelog_no_users_who_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagelog",
            name="no_users_who_received",
            field=models.IntegerField(
                default=0,
                help_text="Number of users who were connected to receive this message when it was sent",
            ),
        ),
    ]
