# Generated by Django

from django.db import migrations


def create_initial_data(apps, schema_editor):
    OperatingRoom = apps.get_model('hospital', 'OperatingRoom')
    Ward = apps.get_model('hospital', 'Ward')
    Role = apps.get_model('hospital', 'Role')

    # Create operating rooms
    OperatingRoom.objects.bulk_create([
        OperatingRoom(name='Sala A'),
        OperatingRoom(name='Sala B'),
        OperatingRoom(name='Sala C'),
        OperatingRoom(name='Endoskopia'),
        OperatingRoom(name='Sala O'),
    ])

    # Create wards
    Ward.objects.bulk_create([
        Ward(name='Orthopedics'),
        Ward(name='Surgery'),
        Ward(name='Burns'),
        Ward(name='Burn ICU'),
        Ward(name='ICU'),
        Ward(name='Endoscopy'),
        Ward(name='Internal medicine'),
    ])

    # Create roles
    Role.objects.bulk_create([
        Role(name='Nurse'),
        Role(name='Anesthetist'),
        Role(name='Surgeon'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]