# Generated by Django 5.2.7 on 2025-10-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_create_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatingroom",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="operatingroom",
            name="name_pl",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="role",
            name="name_en",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="role",
            name="name_pl",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="ward",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="ward",
            name="name_pl",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
