# Generated by Django 5.2.7 on 2025-10-04 15:57

from django.db import migrations


def update_translations(apps, schema_editor):
    Role = apps.get_model('hospital', 'Role')
    OperatingRoom = apps.get_model('hospital', 'OperatingRoom')
    Ward = apps.get_model('hospital', 'Ward')

    # Update role translations
    for role in Role.objects.all():
        if role.name == 'Anesthetist':
            role.name_pl = 'Anestezjolog'
        elif role.name == 'Nurse':
            role.name_pl = 'Pielęgniarka'
        elif role.name == 'Surgeon':
            role.name_pl = 'Chirurg'
        role.save()

    # Update operating room translations
    for or_obj in OperatingRoom.objects.all():
        if 'Sala' in or_obj.name or 'OR' in or_obj.name:
            or_obj.name_pl = or_obj.name.replace('OR', 'Sala operacyjna').replace('Operating Room', 'Sala operacyjna')
        else:
            or_obj.name_pl = f"Sala operacyjna {or_obj.name}"
        or_obj.save()

    # Update ward translations
    for ward in Ward.objects.all():
        if ward.name.lower() == 'ward':
            ward.name_pl = 'Odział'
        elif ward.name.lower() == 'ward a':
            ward.name_pl = 'Odział A'
        elif ward.name.lower() == 'ward b':
            ward.name_pl = 'Odział B'
        elif ward.name.lower() == 'ward c':
            ward.name_pl = 'Odział C'
        else:
            ward.name_pl = ward.name.replace('Ward', 'Odział')
        ward.save()


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_operatingroom_name_en_operatingroom_name_pl_and_more"),
    ]

    operations = [
        migrations.RunPython(update_translations),
    ]
