# Generated by Django 5.2.7 on 2025-10-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0004_update_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="ward",
            name="telephone",
            field=models.CharField(
                blank=True,
                help_text="Ward contact telephone number",
                max_length=20,
                null=True,
            ),
        ),
    ]
