# Generated by Django 5.2.7 on 2025-10-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_ward_telephone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ward",
            name="telephone",
        ),
        migrations.AddField(
            model_name="ward",
            name="nurse_telephone",
            field=models.CharField(
                blank=True,
                help_text="Telephone number to page nurses",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="surgeon_telephone",
            field=models.CharField(
                blank=True,
                help_text="Telephone number to page surgeons",
                max_length=20,
                null=True,
            ),
        ),
    ]
