# Generated by Django 5.2.7 on 2025-10-04 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0006_remove_ward_telephone_ward_nurse_telephone_and_more"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ward",
            name="nurse_telephone",
        ),
        migrations.RemoveField(
            model_name="ward",
            name="surgeon_telephone",
        ),
        migrations.AddField(
            model_name="ward",
            name="telephone",
            field=models.CharField(
                blank=True,
                help_text="Ward contact telephone number",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(max_length=50)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital",
                        to="sites.site",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="operatingroom",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="hospital.hospital",
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="hospital.hospital",
            ),
        ),
    ]
