# Generated by Django 5.2.7 on 2025-10-04 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0008_alter_ward_nurse_telephone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatingroom",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="hospital.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="hospital.hospital",
            ),
        ),
    ]
