# Generated by Django 5.2.7 on 2025-10-09 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0009_alter_operatingroom_hospital_alter_ward_hospital"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can administer this hospital (not superusers)",
                related_name="administered_hospitals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
