# Generated by Django 5.2.7 on 2025-10-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0010_hospital_admins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatingroom",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="operatingroom",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="operatingroom",
            name="name_pl",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ward",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ward",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ward",
            name="name_pl",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="operatingroom",
            unique_together={("name", "hospital")},
        ),
        migrations.AlterUniqueTogether(
            name="ward",
            unique_together={("name", "hospital")},
        ),
    ]
