# Generated by Django 5.2.7 on 2025-10-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hospital",
            "0011_alter_operatingroom_name_alter_operatingroom_name_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="operatingroom",
            name="sort",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Sort order for displaying operating rooms",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="sort",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Sort order for displaying wards", null=True
            ),
        ),
    ]
